version: '3.8'

services:
  restaurant-menu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-menu-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - API_URL=http://restaurant-api:8000
      - REDIS_URL=redis://redis_cache_prod:6379
    networks:
      - app_network_prod
    restart: unless-stopped

networks:
  app_network_prod:
    external: true 