version: '3.8'

services:
  restaurant-menu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-menu
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - ORIGIN=https://pos.capybarasolutions.com
      - API_URL=http://restaurant-api:8000
    networks:
      - app_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app_network_prod:
    external: true 